//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeerRecipe.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Malt_List {
            get {
                return ((string)(this["Malt_List"]));
            }
            set {
                this["Malt_List"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Malt_Filter {
            get {
                return ((string)(this["Malt_Filter"]));
            }
            set {
                this["Malt_Filter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public double Malt_Percentage {
            get {
                return ((double)(this["Malt_Percentage"]));
            }
            set {
                this["Malt_Percentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public double Recipe_BatchVolum {
            get {
                return ((double)(this["Recipe_BatchVolum"]));
            }
            set {
                this["Recipe_BatchVolum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.04")]
        public double Recipe_OriginalGravity {
            get {
                return ((double)(this["Recipe_OriginalGravity"]));
            }
            set {
                this["Recipe_OriginalGravity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public double Recipe_BoilTime {
            get {
                return ((double)(this["Recipe_BoilTime"]));
            }
            set {
                this["Recipe_BoilTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.5")]
        public double Recipe_BoilOfRate {
            get {
                return ((double)(this["Recipe_BoilOfRate"]));
            }
            set {
                this["Recipe_BoilOfRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public double Recipe_BHE {
            get {
                return ((double)(this["Recipe_BHE"]));
            }
            set {
                this["Recipe_BHE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public double Recipe_WLIG {
            get {
                return ((double)(this["Recipe_WLIG"]));
            }
            set {
                this["Recipe_WLIG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double Recipe_WGR {
            get {
                return ((double)(this["Recipe_WGR"]));
            }
            set {
                this["Recipe_WGR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double Recipe_FermenterTrubLoss {
            get {
                return ((double)(this["Recipe_FermenterTrubLoss"]));
            }
            set {
                this["Recipe_FermenterTrubLoss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.5")]
        public double Recipe_KettleLoss {
            get {
                return ((double)(this["Recipe_KettleLoss"]));
            }
            set {
                this["Recipe_KettleLoss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Recipe_AdjustForVolTempChangeInWater {
            get {
                return ((bool)(this["Recipe_AdjustForVolTempChangeInWater"]));
            }
            set {
                this["Recipe_AdjustForVolTempChangeInWater"] = value;
            }
        }
    }
}
